# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5124777d9538c1ae9fef0003bae4d009dc2b5d2f7da070bf91628e87d3f245965471740f737590a6537a687fbc66bd61ee3ebcafec82f75c021b89bbd51aa87

test:
  secret_key_base: e3a25e8cf77d38ece235762f4bc5beaf9f87758be3d05dba4bc9bcd842b5b80d8c454a1517b00a35ccf0120d8076cb49450811bbc14911d677b75fbeb822d380

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
